{
  "formatVersion": "1.1",
  "component": {
    "group": "me.TechsCode",
    "module": "GradleBasePlugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "GradleBasePlugin-1.0.jar",
          "url": "GradleBasePlugin-1.0.jar",
          "size": 21472,
          "sha512": "1a8d2ad1249b76a84c3da891924cf01ad11726ded97792518e1e18cf9fb23bb16c5c19f8cd70bf5ae3aca5f239dd4b47c0c84333d505c22ce3b80af09c5ba974",
          "sha256": "f21b33964dba92034c38fa989f106b6d6b4ac4457a1a67520dd8a97f7ef05f51",
          "sha1": "e3aadd89386cfb5cd894ef64f0b3d4f993eb7cbc",
          "md5": "832ef9bcc59c5a6564acaf08a88bda5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.jcraft",
          "module": "jsch",
          "version": {
            "requires": "0.1.55"
          }
        },
        {
          "group": "com.github.johnrengelman.shadow",
          "module": "com.github.johnrengelman.shadow.gradle.plugin",
          "version": {
            "requires": "7.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "GradleBasePlugin-1.0.jar",
          "url": "GradleBasePlugin-1.0.jar",
          "size": 21472,
          "sha512": "1a8d2ad1249b76a84c3da891924cf01ad11726ded97792518e1e18cf9fb23bb16c5c19f8cd70bf5ae3aca5f239dd4b47c0c84333d505c22ce3b80af09c5ba974",
          "sha256": "f21b33964dba92034c38fa989f106b6d6b4ac4457a1a67520dd8a97f7ef05f51",
          "sha1": "e3aadd89386cfb5cd894ef64f0b3d4f993eb7cbc",
          "md5": "832ef9bcc59c5a6564acaf08a88bda5c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "GradleBasePlugin-1.0-all.jar",
          "url": "GradleBasePlugin-1.0-all.jar",
          "size": 12406857,
          "sha512": "f80c078e4a528e8b700da53c69d08752b1b958f49fa2c5add9bf76d09e0a8ded66bf568b78869a46e26146d588c0fd4c7c837bc0accb04bfe2643532ed6c5d4d",
          "sha256": "2847d1710d1bcf75db6d30b907720a8811fbcd54fd40a246c22374be79649ade",
          "sha1": "ced7e97f68d65ea583b77260393f9dfee74c0eb5",
          "md5": "2d6063886fca44eefa0bfb1c7a705a73"
        }
      ]
    }
  ]
}
